import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Physical AI & Humanoid Robotics Hackathon
  physicalAIHackathonSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics Hackathon',
      items: [
        'physical-ai-hackathon/index',
        'physical-ai-hackathon/embodied-intelligence',
        'physical-ai-hackathon/why-physical-ai-matters',
        'physical-ai-hackathon/course-goals',
        'physical-ai-hackathon/weekly-journey',
        'physical-ai-hackathon/conceptual-architecture',
        'physical-ai-hackathon/lab-architecture',
        'physical-ai-hackathon/assessment-philosophy'
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
